-- select 'Oh no, an SQL just to keep Liquibase happy. ' ||
--        '#hiddenErrors #worksOnMyMachine' from (values(0));

-- 1. Create table WORK_LOG
CREATE TABLE WORK_LOG (
  ID INTEGER NOT NULL IDENTITY,
  START_TIME TIMESTAMP NOT NULL,
  END_TIME TIMESTAMP NOT NULL,
  REF_REPAIR_JOB INTEGER NOT NULL,
  MECHANIC VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(350) NOT NULL,
  PRIMARY KEY (ID)
);

-- 2. Create table SPARE_PART
CREATE TABLE SPARE_PART (
  ID INTEGER NOT NULL IDENTITY,
  REF_REPAIR_JOB INTEGER NOT NULL,
  NAME VARCHAR(350) NOT NULL,
  PRIMARY KEY (ID)
);

